name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  testsuite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.1"]
    name: PHP ${{ matrix.php-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_sqlite
          tools: cs2pr
          coverage: pcov

      - name: Composer install
        run: composer update

      - name: Run PHPUnit
        run: |
          vendor/bin/phpunit
          export CODECOVERAGE=1
          vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Submit code coverage
        if: matrix.php-version == '8.1'
        uses: codecov/codecov-action@v1

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs --standard=CakePHP --report=checkstyle src/ tests/ | cs2pr

      - name: Run phpstan
        if: success() || failure()
        run: vendor/bin/phpstan.phar analyse --error-format=github
