name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  testsuite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1']
    name: PHP ${{ matrix.php-version }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pdo_sqlite
        coverage: none
        
    - name: Composer install
      run: |
        if [[ ${{ matrix.php-version }} == '8.1' ]]; then
          composer update --ignore-platform-reqs
        else
          composer update
        fi
        composer run-script post-install-cmd --no-interaction
    
    - name: Run PHPUnit
      run: |
        vendor/bin/phpunit
